#!/usr/bin/env python3
# ai-generated: 100% - Claude Code (Fable 5.1) wrote the six candidate resolutions from design/LAB1.md section 2; the lecturer reviewed the reasoning and ran the script for all eight combinations
"""Write DECISIONS.md (LAB1.md section 2.1) for any of the eight resolution combinations.

    python make_decisions.py C1 C2 C3 [--output PATH]

    C1: wallclock | business      C2: reopen | immutable      C3: matrix | vip

The prose for each admissible resolution is a real decision record: the reasoning, the service owner who
signs it off and the customer outcome it favours. The shipped DECISIONS.md is this script's output for the
reference defaults (wallclock, immutable, vip); tests/test_repo.py checks that they never drift apart.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

ADMISSIBLE: dict[str, tuple[str, str]] = {
    "C1": ("wallclock", "business"),
    "C2": ("reopen", "immutable"),
    "C3": ("matrix", "vip"),
}

TITLES = {
    "C1": "SLA clock for P1",
    "C2": "Closed tickets and reopening",
    "C3": "VIP reporters and the priority matrix",
}

LABELS = ("Decision", "Rejected alternative", "Reason", "Service owner", "Customer outcome")

TEXTS: dict[tuple[str, str], dict[str, str]] = {
    ("C1", "wallclock"): {
        "Decision":
            "P1 acknowledgement (15 min) and resolution (4 h) run on the wall clock, around the clock; P2 to P4 "
            "targets pause outside business hours (Monday to Friday, 08:00 to 16:00 Europe/Warsaw). The minimal "
            "conflicting part of R-13, the words \"any SLA target\", is narrowed to \"any P2 to P4 target\"; the rest "
            "of R-13 and all of R-14 stand.",
        "Rejected alternative":
            "Every priority, including P1, pauses outside business hours, so that a P1 raised on Friday at 17:00 "
            "is due for acknowledgement on Monday at 08:15 (R-14's \"around the clock\" rejected).",
        "Reason":
            "R-14 exists because a P1 means the whole organisation has stopped work. An SLA that lets a "
            "Friday-evening outage wait until Monday measures nothing the customer cares about, and it makes the "
            "one target with a pager behind it meaningless for 128 of the 168 hours in a week. Narrowing R-13 to "
            "P2 to P4 keeps its purpose, which is not to penalise the desk for hours it is not staffed for routine "
            "work, while keeping the single promise that justifies an on-call rota. It also matches how the desk "
            "is staffed: on-call covers P1 only, so a wall-clock target for P2 to P4 would generate breaches "
            "nobody is rostered to prevent.",
        "Service owner":
            "The Service Desk Manager, who owns the incident management practice, staffs the P1 on-call rota and "
            "signs the SLA with the business; the Service Level Manager countersigns the target table.",
        "Customer outcome":
            "A P1 raised on Friday at 17:00 is acknowledged by 17:15 and worked until resolved; the customer whose "
            "organisation has stopped is never told to wait for Monday. Customers with P2 to P4 issues get the "
            "published business-hours targets, which are the ones the desk can actually staff and report on "
            "honestly.",
    },
    ("C1", "business"): {
        "Decision":
            "Every priority, including P1, runs on the business-hours clock (Monday to Friday, 08:00 to 16:00 "
            "Europe/Warsaw). The minimal conflicting part of R-14, the words \"around the clock\" and the Friday "
            "evening example, is rejected; its 15-minute and 4-hour P1 targets are kept and consumed from business "
            "hours only. All of R-13 stands.",
        "Rejected alternative":
            "P1 targets run on the wall clock around the clock while P2 to P4 pause outside business hours "
            "(R-13's \"any SLA target\" narrowed to P2 to P4).",
        "Reason":
            "The desk described in the requirements has no 24x7 staffing and no on-call rota. A wall-clock P1 "
            "target that nobody is rostered to meet is a breach generated by the calendar, not by the desk, and "
            "those breaches would be noise that hides the real misses in every SLA report. One clock for all "
            "priorities keeps the SLA explainable in one sentence and the pause semantics uniform. If the business "
            "wants 24x7 P1 coverage, that is a staffing and budget decision to be taken as a separate change, and "
            "the wall-clock target is reintroduced the day the rota exists.",
        "Service owner":
            "The Service Desk Manager, who owns the SLA and the staffing model behind it and is accountable for "
            "the breach reports being an honest picture of the desk's performance.",
        "Customer outcome":
            "A P1 raised on Friday at 17:00 has its 15 minutes start on Monday at 08:00; the customer gets a target "
            "the desk can meet, reported truthfully, instead of a promise of 24x7 that nobody is paid to keep. "
            "Inside business hours P1 handling is unchanged and still the fastest the desk offers.",
    },
    ("C2", "reopen"): {
        "Decision":
            "A reporter may reopen a resolved ticket within 7 days of resolved_at and a closed ticket within 7 "
            "days of closed_at; the ticket returns to in_progress and its resolution target is unchanged. The "
            "minimal conflicting part of R-09, the word \"immutable\", is narrowed to \"immutable once the 7-day "
            "window has passed\"; the related_to route in R-09 stays available for older tickets. All of R-10 "
            "stands.",
        "Rejected alternative":
            "A closed ticket can never be reopened; after closure the only route is a new ticket that references "
            "the closed one via related_to (R-10's \"or closed\" rejected).",
        "Reason":
            "Reporters do not distinguish resolved from closed; they know whether the fix worked. Forcing a new "
            "ticket for a fix that failed two days after closure pushes the cost of a process detail onto the "
            "customer, creates duplicate records the desk has to link by hand, and hides the reopen count the "
            "desk needs in order to measure fix quality. The 7-day window bounds the mutability: records older "
            "than a week are frozen, so the reporting concern behind R-09 is fully met after that point, and "
            "the monthly SLA report is only ever computed over frozen records.",
        "Service owner":
            "The Incident Manager, process owner of incident management, who owns the reopen policy because it "
            "defines when the desk's own work counts as complete.",
        "Customer outcome":
            "A customer whose fix failed within a week reopens the same ticket whether or not the desk already "
            "closed it, keeps the same reference number and history, and does not have to explain the issue "
            "again to a new agent.",
    },
    ("C2", "immutable"): {
        "Decision":
            "A closed ticket is immutable. Reopen works from resolved only, within 7 days of resolved_at; a "
            "reopen request on a closed ticket answers 409 whatever its age, and further work on the same issue "
            "is a new ticket that references the closed one via related_to. The minimal conflicting part of R-10, "
            "the words \"or closed\" and \"or closure\", is rejected; reopening a resolved ticket, the rest of "
            "R-10, stands together with all of R-09.",
        "Rejected alternative":
            "Reopen allowed from closed as well, within 7 days of closed_at, with the record becoming immutable "
            "only after that window.",
        "Reason":
            "Closure is the point where the record becomes evidence: it feeds SLA attainment reports, problem "
            "records and the monthly service review, and a record that can silently change after that point makes "
            "every report reproducible only by luck. The 7-day reopen window after resolution already gives the "
            "reporter the \"the fix did not work\" path that R-10 is for; the resolved state exists precisely so "
            "that closure can wait until the reporter has confirmed. A new ticket linked via related_to preserves "
            "the history of both records and gives problem management a countable signal, how many closed tickets "
            "spawned follow-up work, instead of a mutated one.",
        "Service owner":
            "The Incident Manager, process owner of incident management, who signs off the closure rules because "
            "closure is what makes the incident record trustworthy for reporting and problem management.",
        "Customer outcome":
            "A reporter whose fix failed within a week reopens the resolved ticket without friction; once the "
            "ticket is closed, the customer raises a linked ticket and the history of both is preserved, so the "
            "reports the customer relies on (SLA attainment, recurring issues) stay true.",
    },
    ("C3", "matrix"): {
        "Decision":
            "The impact and urgency matrix alone decides the priority. reporter.vip is stored and returned but "
            "never changes the priority; the desk board shows the flag so that VIP tickets stay visible. The "
            "minimal conflicting part of R-06, the uplift \"never lower than P2\", is rejected; its visibility "
            "goal is met by the stored flag. All of R-05 stands.",
        "Rejected alternative":
            "After the matrix, a VIP ticket at P3 or P4 is raised to P2 while P1 and P2 are unchanged (R-05's "
            "\"from nothing else\" narrowed to \"from nothing the client sends as a priority\").",
        "Reason":
            "Priority is the one number that drives SLA targets and the order of work, and R-05 exists so that "
            "the number is explainable from the impact and urgency of the incident itself. A VIP uplift makes the "
            "SLA report say the desk is slower on P2 than it is, because part of the P2 queue is P4 work in "
            "disguise, and it silently reorders the queue by seniority instead of by impact. The visibility that "
            "R-06 asks for is a display concern: a queue filter on the stored flag gives the desk the same "
            "immediate view without corrupting the SLA data.",
        "Service owner":
            "The Service Level Manager, who owns the SLA definitions and the reports built on them and is "
            "accountable for priority meaning the same thing on every ticket.",
        "Customer outcome":
            "Every reporter, executive or not, gets the priority that the impact and urgency of the incident "
            "justify, and the SLA report the business reads is about incidents, not about who raised them; "
            "VIP tickets remain visible to the desk through the flag.",
    },
    ("C3", "vip"): {
        "Decision":
            "After the matrix, a ticket whose reporter has vip = true and that landed on P3 or P4 is raised to P2; "
            "P1 and P2 are unchanged. The minimal conflicting part of R-05, the words \"from nothing else\", is "
            "narrowed to \"from nothing the client sends as a priority\": a priority field in the request is still "
            "ignored, and neither reporter nor agent can request one. All of R-06 stands.",
        "Rejected alternative":
            "The matrix alone decides and reporter.vip is stored but ignored; VIP visibility is handled by a "
            "queue filter on the flag (R-06's uplift rejected).",
        "Reason":
            "The purpose of R-05 is to stop reporters and agents negotiating priorities ticket by ticket. The VIP "
            "flag is not such a negotiation: it is a standing decision by management about a small set of people "
            "whose blocked work has an outsized business cost, and it is maintained by the desk, not chosen by the "
            "reporter. Capping the uplift at P2 keeps P1 reserved for genuine organisation-wide impact, so the "
            "on-call rota is never paged for an executive's cosmetic issue, while the ticket reaches the desk "
            "board within the hour, which is the whole point of R-06.",
        "Service owner":
            "The Service Desk Manager, who owns the desk's queue policy and maintains the VIP list together with "
            "the business relationship manager; the Service Level Manager is informed because P2 volumes change.",
        "Customer outcome":
            "An executive's blocked laptop is seen within the hour instead of by the end of the day, without "
            "displacing an organisation-wide outage; every other reporter keeps the published matrix and can see "
            "exactly why a ticket has the priority it has.",
    },
}

INTRO = (
    "The requirements document contains three pairs of requirements that cannot both hold: R-13 and R-14 (which "
    "clock the P1 targets run on), R-09 and R-10 (whether a closed ticket can be reopened) and R-05 and R-06 "
    "(whether a VIP reporter changes the priority). Each conflict is resolved by rejecting the minimal conflicting "
    "part of one requirement and keeping everything else in the pair, so both sides of each pair are still "
    "implemented and tested. The running service exhibits exactly the combination declared in the front matter: "
    "`SVCDESK_C1`, `SVCDESK_C2` and `SVCDESK_C3` switch the service, and `python make_decisions.py C1 C2 C3` "
    "regenerates this file so the declaration and the behaviour never disagree."
)


def _wrap(text: str) -> str:
    return "\n".join(textwrap.wrap(text, width=110, break_long_words=False, break_on_hyphens=False))


def render(c1: str, c2: str, c3: str) -> str:
    values = {"C1": c1, "C2": c2, "C3": c3}
    for key, value in values.items():
        if value not in ADMISSIBLE[key]:
            raise ValueError(f"{key}={value!r} is not admissible; use one of {' | '.join(ADMISSIBLE[key])}")
    lines = [
        "---",
        "svcdesk_decisions:",
        f"  C1: {c1:<12} # wallclock | business",
        f"  C2: {c2:<12} # reopen | immutable",
        f"  C3: {c3:<12} # matrix | vip",
        "---",
        "<!-- ai-generated: 100% - Claude Code (Fable 5.1) wrote the six candidate resolutions in make_decisions.py "
        f"from design/LAB1.md section 2; this file is its output for C1={c1} C2={c2} C3={c3} -->",
        "",
        "# Decisions",
        "",
        _wrap(INTRO),
        "",
    ]
    for key in ("C1", "C2", "C3"):
        lines.append(f"## {key} - {TITLES[key]}")
        lines.append("")
        for label in LABELS:
            lines.append(_wrap(f"**{label}:** {TEXTS[(key, values[key])][label]}"))
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="write DECISIONS.md for a resolution combination")
    parser.add_argument("c1", metavar="C1", help="wallclock | business")
    parser.add_argument("c2", metavar="C2", help="reopen | immutable")
    parser.add_argument("c3", metavar="C3", help="matrix | vip")
    parser.add_argument("--output", default=str(Path(__file__).resolve().parent / "DECISIONS.md"),
                        help="where to write (default: DECISIONS.md next to this script)")
    args = parser.parse_args(argv)
    try:
        text = render(args.c1.lower(), args.c2.lower(), args.c3.lower())
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    Path(args.output).write_text(text, encoding="utf-8")
    print(f"wrote {args.output}: C1={args.c1.lower()} C2={args.c2.lower()} C3={args.c3.lower()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
